### ISSUE TITLE
Croatian letters not showing correctly

### ISSUE THREAD

**Issue by cicnavi** [smalot/pdfparser#152]
Hello, thanks for creating this great package.
When converting from PDF to text, some letters commonly used in Croatian language are converted to some letters which are never used in Croatian language.
For example, letter "đ" becomes "Ď", letter "ž" becomes "ţ". The correct way would be that the letter "đ" stays "đ", and the same is with letter "ž". Is it possible to correct this?
Here is the PDF I tried to extract text from:
[Dumic_Mak.pdf](https://github.com/smalot/pdfparser/files/1024775/Dumic_Mak.pdf)
Thanks,
Marko

**Comment by davispuh** [comment]
Try #257 PR it should be fixed there.

**Comment by Connum** [comment]
I'm in the process of reviving #257 in a new PR. However, this issue is not solved by it.

Interestingly, when copy/pasting a word like `istraživanja` from the PDF in Acrobat DC into any text editor or input field, it becomes: `istraţivanja`. An using the search functionality of Acrobat DC or when viewing the PDF in a browser, one can search for `istraţivanja` and the word looking like `istraţivanja` will be highlighted.

Even more interestingly, when searching for `istraživanja` explicitly, there is only one instance of this word that is actually being highlighted (on page 28), despite the word appearing several times throughout the document. And this one instance is also correct when decoded by pdfparser:
![grafik](https://user-images.githubusercontent.com/13076806/94605168-0316a680-0299-11eb-820e-29403a1b0699.png)

**So it seems like the font that this PDF uses is actually substituting characters for each other. What looks like a `ž` is actually a `ţ` and therefore, it's correctly parsed as a `ţ` by pdfparser.** 

I don't think we can work around that in any way... The only thing that comes to my mind would be analyzing each glyph of the font and apply some kind of character recognition, but of course that's not feasible.

**Comment by k00ni** [comment]
Thank you @Connum for checking that. I follow your argument, therefore issue is closed. If the problem persists, please reopen.
