### ISSUE TITLE
UTF-8 autodetection not working?

### ISSUE THREAD

**Issue by ThomasLandauer** [smalot/pdfparser#202]
On some documents, I *need* to do `utf8_encode()` on the result of `getText()`, on some documents I *must not* do `utf8_encode()`, and on some it doesn't work either way ;-)

Looks like the encoding is somehow "autodetected"? How is this mechanism working and how can I adjust it?

**Comment by davispuh** [comment]
Try #257 PR it should be fixed there.

**Comment by Connum** [comment]
@ThomasLandauer I know it's been 2 years, but could you please try to provide a PDF with which I could reproduce this issue, or verify that it has been fixed in the meantime? I would very much like to find out whether #257 could have an impact here and would be worth being revived.

**Comment by ThomasLandauer** [comment]
I would say the issue is still there. Here's an example: [test.pdf](https://github.com/smalot/pdfparser/files/5304153/test.pdf)

Expected outcome:
> „fööbär“

Actual outcome:
> �f��b�r�

I created the PDF with [dompdf](https://github.com/dompdf/dompdf) - here's the code (Symfony Controller):

```php
$dompdf = new Dompdf();
$dompdf->setPaper('A4', 'portrait');
$dompdf->loadHtml('<html><head><meta charset="utf-8"></head><body>„fööbär“</body></html>');
$dompdf->render();
$pdf = $dompdf->output();
file_put_contents('test.pdf', $pdf);

$parser = new \Smalot\PdfParser\Parser();
$pdf = $parser->parseFile('test.pdf');
$text = $pdf->getText();
return new Response("<html><head><meta charset='utf-8'></head><body>$text</body></html>");
```
Deleting both `<meta charset='utf-8'>` doesn't make a difference.
I have smalot/pdfparser v0.16.2

**Comment by Connum** [comment]
I can confirm that this issue persists with the current master. It is however fixed by #257, which was closed due to inactivity. I'm working on reviving this with a new PR that addresses the failing and missing tests. Thanks for the sample, I'll be using it for the unit test!

**Comment by k00ni** [comment]
@ThomasLandauer thank you for your feedback. Just to be sure, what character set / encoding is used in your Symfony application for the output?

**Comment by ThomasLandauer** [comment]
> Thanks for the sample, I'll be using it for the unit test!

Yeah, fööbär forever! :-)

> Just to be sure, what character set / encoding is used in your Symfony application for the output?

Symfony is UTF-8 by default, see https://symfony.com/doc/current/reference/configuration/kernel.html#charset (and I just double-checked that I didn't change anything in there). Besides, the best "proof" probably is to open the PDF in some PDF viewer :-)
